server:
  port: 8080

spring:

  jpa:
    database: mysql
    generate-ddl: true
    hibernate.ddl-auto: update
    hibernate:
      use-new-id-generator-mappings: true
  datasource:
    url: jdbc:mysql://localhost:3306/ppmtool?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: