server:
  port: 8080

spring:

  jpa:
    database: mysql
    generate-ddl: true
    hibernate.ddl-auto: update
    hibernate:
      use-new-id-generator-mappings: true
  datasource:
#    url: jdbc:mysql://localhost:3306/ppmtool?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mysql://us-cdbr-iron-east-02.cleardb.net/heroku_5be89dcd213987f?reconnect=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: babcf2e48105a2
    password: 3a88846a